# Default application configuration that all configurations inherit from.

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: true
    max_elements: 3

  BorderZero:
    enabled: true
    convention: none # or `zero`, or `none`

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true
    style: silent

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: true

  DuplicateProperty:
    enabled: true
    ignore_consecutive:
    - background
    - transition

  ElsePlacement:
    enabled: true
    style: same_line # or 'same_line', or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: long # or 'short', or 'long'

  HexNotation:
    enabled: true
    style: uppercase # or 'lowercase', or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'space', or 'tab'
    width: 2

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'exclude_zero', or 'include_zero'

  LengthVariable:
    enabled: true
    allowed_lengths: 100vh, 100vw
    allowed_properties: text-shadow, box-shadow

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: snake_case # or 'camel_case', or 'snake_case', or 'hyphenated_lowercase', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 5
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: true

  PrivateNamingConvention:
    enabled: false
    prefix: _

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  # hier muss noch gesprochen werden ob und wie die ordnung aussehen muss
  PropertySortOrder:
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false

  PropertySpelling:
    enabled: true
    extra_properties:
      - some-experimental-property
      - another-experimental-property
    disabled_properties:
      - some-existing-property
      - another-existing-property

  # hier muss noch gesprochen werden welche Units akzeptabel sind
  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties:
      border: ['px'] # Only pixels
      line-height: [] # No units allowed
      margin: ['em', 'rem']

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false

  SelectorDepth:
    enabled: false
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: snake_case # or 'strict_BEM', or 'hyphenated_BEM', or 'hyphenated_lowercase', or 'camel_case', or 'snake_case', or a regex pattern

  Shorthand:
    enabled: false
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true
    style: at_least_one_space # or 'one_space', or 'no_space', or 'at_least_one_space'

  SpaceAfterComment:
    enabled: true
    style: one_space # or 'one_space', or 'no_space', or 'at_least_one_space'
    allow_empty_comments: true

  SpaceAfterPropertyColon:
    enabled: true
    style: at_least_one_space # or 'one_space', or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: false
    style: at_least_one_space # or 'one_space', or 'no_space', 'at_least_one_space' or 'one_space_or_newline'

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'one_space', or 'at_least_one_space', or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line', or 'space'
    allow_single_line_padding: true

  SpaceBetweenParens:
    enabled: true
    spaces: 1

  StringQuotes:
    enabled: false
    style: double_quotes # or single_quotes, or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  # hier muss noch gesprochen werden welche Elemente IMMER Variablen haben müssen
  VariableForProperty:
    enabled: true
    properties:
      - color
      - font

  # hier muss noch gesprochen werden wird ein Autoprefixer genutzt (Compass Bourbon) oder eigene Mixins
  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false